//
//  DailyReminderNotifications.swift
//  one-percent-better
//
//  Created by Jeremy Cook on 3/3/23.
//

import Foundation

class DailyReminderNotifications {
   static let messages = [
      "Track your way to success!",
      "Make it a habit to track your habits.",
      "Track your habits and watch yourself grow!",
      "Create your own success story.",
      "Progress begins with tracking.",
      "Keep track of your progress.",
      "Track your habits and unlock your potential.",
      "Get organized with habit tracking.",
      "Set yourself up to succeed.",
      "Track and reach your goals.",
      "Monitor your progress and stay motivated.",
      "Keep your habits on track.",
      "Step up your game with habit tracking.",
      "Make tracking a priority.",
      "Make tracking part of your life.",
      "Make tracking your habit.",
      "Keep an eye on your habits.",
      "Track for success.",
      "Reach your goals with tracking.",
      "Track your daily habits.",
      "Track and thrive.",
      "Track to get ahead.",
      "Track and stay on top.",
      "Get ahead with tracking.",
      "Track to reach your goals.",
      "Take control with tracking.",
      "Make tracking your superpower.",
      "Maximize your potential with tracking.",
      "Get organized and reach your goals.",
      "Track your way to greatness.",
      "Reach your goals with tracking.",
      "Track and be inspired.",
      "Reach new heights with tracking.",
      "Create your own success story.",
      "Reach your goals with tracking.",
      "Track and stay motivated.",
      "Track your progress and stay on track.",
      "Monitor your progress and keep going.",
      "Track to unlock your potential.",
      "Track your progress and triumph.",
      "Conquer your goals with tracking.",
      "Stay focused with tracking.",
      "Track and get ahead.",
      "Track and reach your dreams.",
      "Reach your goals with tracking.",
      "Take charge with tracking.",
      "Track and make your dreams a reality.",
      "Make tracking part of your routine.",
      "Track your way to success!",
      "Be proud of your progress! Keep going!",
      "A journey of a thousand miles begins with a single step!",
      "You can do it! Take that next step.",
      "Every habit starts with a single action. Do it!",
      "You are stronger than your excuses. Keep going!",
      "Don't give up! You're almost there.",
      "Don't wait for motivation. Take action now.",
      "Small steps lead to big changes. Keep going!",
      "Believe in yourself. You can do it.",
      "Every habit is a victory. Celebrate it!",
      "Success is in the effort. Keep going!",
      "You got this! Take the next step.",
      "Don't be afraid to push yourself.",
      "Change your life one habit at a time.",
      "Stay focused. You can do it.",
      "Keep going. You'll get there soon.",
      "Every habit is a success. Celebrate it!",
      "Don't give up. You can do it.",
      "Believe in your ability to succeed.",
      "Take action. You are capable.",
      "Every habit starts with a single action.",
      "Stay motivated. You can do it.",
      "Don't wait for the perfect moment. Take action now.",
      "Small steps lead to big changes.",
      "Don't be afraid. Trust yourself.",
      "You are closer than you think. Keep going!",
      "Don't let your excuses hold you back.",
      "Believe in your ability to succeed.",
      "Take the next step. You got this!",
      "Success is in the effort.",
      "Take the challenge. You can do it.",
      "Make it a habit. Take action now.",
      "Every habit is a success. Celebrate it!",
      "Small steps lead to big changes. Keep going!",
      "Believe in yourself. You can do it.",
      "Don't give up. You'll get there soon.",
      "You are closer than you think. Stay focused.",
      "Don't wait for motivation. Take action now.",
      "Every habit starts with a single action.",
      "Keep going. You are capable.",
      "Take the next step. You can do it.",
      "Make it a habit. Believe in yourself.",
      "Don't be afraid. Have faith in yourself.",
      "Success is in the effort. You got this!",
      "Take the challenge. Believe in yourself.",
      "Every habit is a victory. Celebrate it!",
      "Stay motivated. You are closer than you think.",
      "Don't let your excuses hold you back.",
      "Make it a habit. Take the next step.",
      "Don't give up. You can do it."
   ]
}
