# Uncomment the next line to define a global platform for your project
platform :ios, '15.4'

target 'one-percent-better' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for one-percent-better
  pod 'Introspect'

  target 'one-percent-betterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'one-percent-betterUITests' do
    # Pods for testing
  end

end
