//
//  MostCommonHabits.swift
//  one-percent-better
//
//  Created by Jeremy Cook on 12/16/22.
//

import Foundation

class PrebuiltHabits {
   
   static let habitNames = ["Exercise",
                            "Eat healthy",
                            "Get enough sleep",
                            "Drink water",
                            "Take vitamins",
                            "Read",
                            "Listen to music",
                            "Meditate",
                            "Yoga",
                            "Take time for myself",
                            "Learn something new",
                            "Spend time with family",
                            "Spend time with friends",
                            "Organize",
                            "Clean",
                            "Declutter",
                            "Make a to-do list",
                            "Wake up early",
                            "Go to bed early",
                            "Save money",
                            "Create a weekly budget",
                            "Create a monthly budget",
                            "Invest",
                            "Get outside",
                            "Take a walk",
                            "Spend time in the sun",
                            "Stretch",
                            "Learn a new language",
                            "Write",
                            "Journal",
                            "Practice an instrument",
                            "Practice gratitude",
                            "Do something creative",
                            "Practice deep breathing",
                            "Listen to a podcast",
                            "Spend time in silence",
                            "Pray",
                            "Practice mindfulness",
                            "Cook meal at home",
                            "Reduce screen time",
                            "Practice self-compassion",
                            "Spend time with animals",
                            "Volunteer",
                            "Practice positive self-talk",
                            "Try something new",
                            "Enjoy the present moment",
                            "Reflect",
                            "Practice good hygiene",
                            "Make time for meaningful conversations",
                            "Practice deep listening",
                            "Practice kindness",
                            "Spiritual practice",
                            "Make time for relationships",
                            "Practice healthy communication",
                            "Connect with friends",
                            "Create a budget",
                            "Eat healthy snacks",
                            "Try a new recipe",
                            "Take a class",
                            "Learn a language",
                            "Explore a new place",
                            "Create something",
                            "Dance",
                            "Take the day off for yourself",
                            "Give back to the community",
                            "Make time for friends"
   ]
}
